cupp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views
from cupp.common import views as common_views
from cupp.point import views as point_views
from cupp.point.views import get_districts, custom_login_redirect
from cupp.license import views_lic as license_views
from cupp.event import views_event as event_views
from cupp.rent import views_rent as rent_views
from cupp.store_consultant import views as sc_views
from cupp.store_trainer import views as st_views
from cupp.competitors import views as comp_views
from cupp.master_api.views import StoreMasterAPI
from cupp.veritech_api.views import fetch_and_save_employee_data
from cupp.dispute import views as leg_views
# from cupp.powerBI_api.views import fetch_powerbi_data

# from cupp.ajax_table_list import ajax_table_list

urlpatterns = [

    path('save/', fetch_and_save_employee_data, name='save_employee_data'),
    # path('power/', fetch_powerbi_data, name='save_powerbi_data'),

    path('api/storemaster/', StoreMasterAPI.as_view(), name='storemaster-api'),

    path('ajax/get_districts/', get_districts, name='ajax_get_districts'),
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),

    # path('ajax/table-data/', ajax_table_list.get_table_data, name='ajax_table_data'),

    path('custom-login-redirect/', custom_login_redirect, name='custom_login_redirect'),

    path('groups/', point_views.display_groups, name='display-groups'),
    path('bi-embed/', point_views.bi_embed, name='bi-embed'),
    path('', point_views.index, name='event_index'),
    # path('register-license/', license_views.MainTableCreateView, name='register_license'),

    path('leg-index/', leg_views.index, name='leg-index'),
    path('leg-add/', leg_views.leg_add, name='leg-add'),
    path('leg-edit/<int:id>', leg_views.edit, name='leg-edit'),
    path('leg-update/<int:id>', leg_views.update, name='leg-update'),
    path('leg-delete/<int:id>', leg_views.destroy, name='leg-delete'),

    path('get-unallocated-stores/', sc_views.get_unallocated_stores, name='get_unallocated_stores'),

    path('sc-index/', sc_views.scIndex, name='sc-index'),
    path('store-index/', sc_views.index, name='store-index'),
    path('sc-view/<int:id>', sc_views.sc_view, name='sc-views'),
    path('sc-edit/<int:id>', sc_views.edit, name='sc-edit'),
    path('sc-update/<int:id>', sc_views.update, name='sc-update'),
    path('update_consultant_area/', sc_views.update_consultant_area, name='update_consultant_area'),
    # path('update_allocation/', sc_views.update_allocation, name='update_allocation'),
    path('save-allocations/', sc_views.save_allocations, name='save_allocations'),
    path('get-allocations/', sc_views.get_allocations, name='get_allocations'),
    path('get-team-data/<int:team_id>/', sc_views.get_team_data, name='get_team_data'),
    path('get-scs-by-team/<int:team_id>/', sc_views.get_scs_by_team, name='get_scs_by_team'),

    path('save-consultant-stores/', sc_views.save_consultant_stores, name='save-consultant-stores'),

    path('log-index/', event_views.index, name='event_index'),
    path('log-create', event_views.event_addnew, name='event-create'),
    path('log-edit/<int:id>', event_views.edit, name='event-edit'),
    path('log-update/<int:id>', event_views.update, name='event_update'),
    path('log-delete/<int:id>', event_views.destroy, name='log-delete'),

    path('comp-index/', comp_views.index, name='comp_index'),
    path('comp-create/', comp_views.comp_addnew, name='comp-create'),
    path('comp-edit/<int:id>', comp_views.edit, name='comp-edit'),
    path('comp-update/<int:id>', comp_views.update, name='comp_update'),
    path('comp-delete/<int:id>', comp_views.destroy, name='comp-delete'),

    path('rent-index/', rent_views.index, name='rent_index'),
    path('rent-create', rent_views.rent_addnew, name='rent-create'),
    path('rent-edit/<int:id>', rent_views.edit, name='rent-edit'),
    path('rent-update/<int:id>', rent_views.update, name='rent-update'),
    path('rent-delete/<int:id>', rent_views.destroy, name='rent-delete'),
    path('api/store-id-search/', rent_views.store_id_search, name='store_id_search'),

    path('st-index/', st_views.index, name='st-index'),
    path('st-view/<int:id>', st_views.st_view, name='st-view'),
    path('st-edit/<int:id>', st_views.edit, name='st-edit'),
    path('st-update/<int:id>', st_views.update, name='st-update'),
    # path('st-delete/<int:id>', st_views.destroy, name='st-delete'),

    path('register-license/', license_views.index, name='index'),
    path('addnew', license_views.addnew, name='addnew'),
    path('lic-edit/<int:id>', license_views.edit, name='lic-edit'),
    path('lic-update/<int:id>', license_views.update, name='lic-update'),
    # path('lic-delete/<int:id>/<str:table>/', license_views.destroy, name='lic-delete'),
    path('lic-delete/<int:id>', license_views.destroy, name='lic-delete'),

    path('map/', common_views.Map.as_view(), name='map'),
    path('my-settings/', common_views.MySettings.as_view(), name='my_settings'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('create/', point_views.Create.as_view(), name='point_create'),
    path('edit/<int:pk>/', point_views.Edit.as_view(), name='point_edit'),
    path('delete/<int:pk>/', point_views.Delete.as_view(), name='point_delete'),
    path('info/<int:pk>/', point_views.AjaxInfo.as_view(), name='point_ajax_info'),
    path('detail/<int:pk>/', point_views.Detail.as_view(), name='point_detail'),
    path('ajax-points/', point_views.AjaxList.as_view(), name='point_ajax_list'),

    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-recover/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-recover/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cupp.point.views.custom_404_view'

admin.site.site_title = 'PP Management'
admin.site.site_header = 'PP Management'
admin.site.index_title = 'Administration'

cupp/license/models.py
from django.db import models

# Create your models here.
from django.db import models
import os
import uuid

from django.db import models as m
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.conf import settings
from uuid import uuid4
from django.utils import timezone

from cupp.point.models import District, City
from cupp.event.models import ActionOwner


class DimensionTable(m.Model):
    lic_id = m.CharField('License type', blank=False, default='', max_length=50)
    lic_id_nm = m.CharField('License type name', blank=False, default='', max_length=50)

    def __str__(self):
        return self.lic_id

    class Meta:
        db_table = 'lic_type'
        verbose_name = 'Dimenstion table'


class MainTable(models.Model):
    five_digit_validator = RegexValidator(r'^\d{5}$', 'Store number must be a 5-digit number')
    store_id = models.CharField(max_length=5, validators=[five_digit_validator], blank=True, null=True)
    lic_id = models.ForeignKey(DimensionTable, on_delete=models.CASCADE, verbose_name='License type', null=True,
                               blank=True)
    lic_id_nm = models.CharField('License Type Name', max_length=50, null=True, blank=True)
    lic_yn = models.BooleanField('Type of rent agreement', null=True, blank=True)
    st_dt = models.DateField('Rent agreement start date', null=True, blank=True)
    ed_dt = models.DateField('License Ended Date', null=True, blank=True)
    lic_owner = models.CharField('Licensed Employee', max_length=50, null=True)
    lic_prov_ID = models.CharField('License Provider ID', max_length=50, blank=True, null=True)
    lic_prov_name = models.CharField('License Provider Name', max_length=50, blank=True, null=True)
    lic_no = models.CharField('License Code', max_length=50, blank=True, null=True)
    alc_opentime = models.TimeField('Time to start selling alcohol', null=True, default=timezone.now, blank=True)
    alc_closetime = models.TimeField('Time to sell out alchohol', null=True, default=timezone.now, blank=True)
    lic_sqrm = models.DecimalField('Licensed area', max_digits=5, decimal_places=1, null=True, blank=True)
    camera_cnt = models.IntegerField('Total number of cameras', default=0, blank=True, null=True)

    alc_type = models.CharField('Type of Alcohol', null=True, blank=True, max_length=10)
    lic_type = models.CharField('Type of License', null=True, blank=True, max_length=10)
    link_path = models.URLField('Link to License Document', blank=True, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, verbose_name='Licensed District', null=True)
    lic_status = models.BooleanField('License Status', null=True, blank=True)
    lic_duration = models.IntegerField('Total Duration of License', null=True, blank=True, default=0)

    created_date = models.DateTimeField('Created date', auto_now_add=True, null=True)
    modified_date = models.DateTimeField('Modified date', auto_now=True, null=True)
    modified_by = models.ForeignKey(User, verbose_name='Modified by', related_name='str_license_modified',
                                    on_delete=models.PROTECT, null=True)
    created_by = models.ForeignKey(User, verbose_name='Created by', related_name='str_license_created',
                                   on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.lic_prov_ID

    def save(self, *args, **kwargs):
        if not self.pk and not self.created_by:
            self.created_by = self.modified_by
        super(MainTable, self).save(*args, **kwargs)

    class Meta:
        db_table = 'str_license'
        verbose_name = 'MainTable'



class DimensionTableLicenseProvider(models.Model):
    lic_id = models.ForeignKey(MainTable, on_delete=models.CASCADE, verbose_name='License Provider ID')
    lic_prov_name = models.CharField('License Provider Name', max_length=50)
    org_add = models.CharField('License Provider Address', max_length=50)
    org_emp_nm = models.CharField('Name of concerned employee', max_length=50)
    org_emp_tel = models.CharField('Name of concerned telephone', max_length=50)
    org_emp_em = models.CharField('Name of concerned employee email', max_length=50)

    def __str__(self):
        return self.lic_id

    class Meta:
        db_table = 'lic_provider'
        verbose_name = 'Dimenstion Table License Provider'

# lic_id_nm = m.ForeignKey(dimension_table.lic_id_nm, on_delete=m.CASCADE, related_name='License name')

cupp/license/forms.py
from django import forms as f
from django.conf import settings
from .models import MainTable
from cupp.point.models import District, City
from cupp.event.models import ActionOwner


class MainTableForm(f.ModelForm):
    st_dt = f.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    ed_dt = f.DateField(input_formats=settings.DATE_INPUT_FORMATS)

    alc_type = f.ChoiceField(choices=[('', '---------'), ('high', 'High'), ('low', 'Low'), ('both', 'Both')],
                             widget=f.Select(attrs={'class': 'form-control'}))
    lic_type = f.ChoiceField(choices=[('', '---------'), ('24H', '24H'), ('17H', '17H')],
                             widget=f.Select(attrs={'class': 'form-control'}))
    # link_path = f.URLField(widget=f.URLInput(attrs={'class': 'form-control'}))
    link_path = f.URLField(required=False, widget=f.URLInput(attrs={'class': 'form-control'}))
    lic_duration = f.IntegerField(widget=f.NumberInput(attrs={'class': 'form-control'}))

    # alc_opentime = f.TimeField(input_formats=settings.TIME_INPUT_FORMATS)
    # alc_closetime = f.TimeField(input_formats=settings.TIME_INPUT_FORMATS)

    class Meta:
        model = MainTable
        fields = ['store_id', 'lic_id', 'lic_id_nm', 'lic_yn', 'st_dt', 'ed_dt', 'lic_owner', 'lic_prov_ID',
                  'lic_prov_name', 'lic_no', 'alc_opentime', 'alc_closetime', 'camera_cnt', 'lic_sqrm', 'alc_type',
                  'lic_type', 'link_path', 'district', 'lic_status', 'lic_duration']
        widgets = {'store_id': f.TextInput(attrs={'class': 'form-control'}),
                   'lic_id_nm': f.TextInput(attrs={'class': 'form-control'}),
                   'lic_owner': f.TextInput(attrs={'class': 'form-control'}),
                   'lic_prov_ID': f.TextInput(attrs={'class': 'form-control'}),
                   'lic_prov_name': f.TextInput(attrs={'class': 'form-control'}),
                   'lic_no': f.TextInput(attrs={'class': 'form-control'}),
                   }

templates/license/ajax_license_list.html
{% for license in object_list %}
    <ul data-id="{{ license.id }}"
        data-store_id="{{ point.store_id }}"
        data-lic_id="{{ point.lic_id }}"
        data-lic_id_nm="{{ point.lic_id_nm }}"
        data-lic_yn="{{ point.lic_yn }}"
        data-st_dt="{{ point.st_dt}}"
        data-ed_dt="{{ point.ed_dt}}"
        data-lic_owner="{{ point.lic_owner}}"
        data-lic_prov_ID="{{ point.lic_prov_ID}}"
        data-lic_prov_name="{{ point.lic_prov_name}}"
        data-lic_no="{{ point.lic_no}}"

        >
    </ul>
{% endfor %}

templates/license/edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block header %}
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <form method="POST" class="post-form" action="{% url 'lic-update' model.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="container">
                <div class="col-12">
                    <h3>Update Details</h3>
                </div>
                <div class="form-group col-md-6">
                    <label>Дугаар: </label>
                    <input type="text" class="form-control" name="id" id="id_id" readonly
                           value="{{ model.id }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Store code: </label>
                    <input type="number" class="form-control" name="store_id" id="id_store_code"
                           value="{{ model.store_id }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Лицензийн төрөл:</label>
                    <select name="lic_id" id="id_lic_id" class="form-control">
                        {% for type in types %}
                            <option value="{{ type.lic_id }}"
                                    {% if type.lic_id == model.lic_id.lic_id %}selected{% endif %}>
                                {{ type.lic_id }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Лицензийн төрлийн нэр:</label>
                    <select name="lic_id_nm" id="id_lic_id_nm" class="form-control">
                        {% for type in types %}
                            <option value="{{ type.lic_id_nm }}"
                                    {% if type.lic_id_nm == model.lic_id_nm %}selected{% endif %}>
                                {{ type.lic_id_nm }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Лицензтэй эсэх: </label>
                    <select class="form-control" name="lic_yn" id="id_lic_yn">
                        <option value="True" {% if model.lic_yn %}selected{% endif %}>Тийм</option>
                        <option value="False" {% if not model.lic_yn %}selected{% endif %}>Үгүй</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Лиценз авсан огноо: </label>
                    <input type="date" class="form-control" name="st_dt" id="id_st_dt"
                           value="{{ model.st_dt|date:"Y-m-d" }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Лиценз дуусах огноо: </label>
                    <input type="date" class="form-control" name="ed_dt" id="id_ed_dt"
                           value="{{ model.ed_dt|date:"Y-m-d" }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Лиценз авсан ажилтан:</label>
                    <input type="text" class="form-control" name="lic_owner" id="id_lic_owner"
                           maxlength="255" value="{{ model.lic_owner }}"/>
                </div>
                <div class="form-group col-md-6 liquor-time">
                    <label>Архи зарж эхлэх цаг: </label>
                    <input type="time" id="id_alc_opentime" name="alc_opentime" class="form-control"
                           value="{{ model.alc_opentime|time:'H:i' }}">
                    {#                    <input type="time" id="id_alc_opentime" name="alc_opentime" class="form-control"#}
                    {#                           value="{{ model.alc_opentime }}">#}
                </div>
                <div class="form-group col-md-6 liquor-time">
                    <label>Архи зарж дуусах цаг:</label>
                    <input type="time" id="id_alc_closetime" name="alc_closetime" class="form-control"
                           value="{{ model.alc_closetime|time:'H:i' }}">
                    {#                    <input type="time" id="id_alc_closetime" name="alc_closetime" class="form-control"#}
                    {#                           value="{{ model.alc_closetime }}">#}
                </div>
                <div class="form-group col-md-6 camera-count">
                    <label>Камерын тоо:</label>
                    <input type="number" id="id_camera_cnt" name="camera_cnt" class="form-control"
                           value="{{ model.camera_cnt }}">
                </div>
                <div class="form-group col-md-6 field-size">
                    <label>Талбайн хэмжээ:</label>
                    <input type="number" id="id_lic_sqrm" name="lic_sqrm" class="form-control"
                           value="{{ model.lic_sqrm }}">
                </div>
                <div class="form-group col-md-6">
                    <label>Лиценз олгосон газрын нэр ID:</label>
                    <input type="text" class="form-control" name="lic_prov_ID" id="id_lic_prov_ID"
                           maxlength="255" value="{{ model.lic_prov_ID }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Лиценз олгосон газар:</label>
                    <input type="text" class="form-control" name="lic_prov_name" id="id_lic_prov_name"
                           maxlength="255" value="{{ model.lic_prov_name }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Лицензийн код:</label>
                    <input type="text" class="form-control" name="lic_no" id="id_lic_no"
                           maxlength="255" value="{{ model.lic_no }}"/>
                </div>
                <div class="form-group col-md-6">
                    <a href="{% url 'index' %}" class="btn btn-link text-purple-300">
                        Cancel
                    </a>
                </div>
                <div class="form-group col-md-6">
                    <button type="submit" class="btn btn-success btn-lg">Update</button>
                </div>
            </div>
        </form>
    </div>{% endblock content %}

templates/license/form.html
{#<link rel="stylesheet" type="text/css"#}
{#      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>#}
{#<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css"/>#}
{% extends "base.html" %}
{% load event_tags %}
{% load widget_tweaks %}

{% block header %}
{% endblock %}
{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <span><a href="/addnew" id="btn_save_and_new"
                         class="btn bg-purple ml-1">Add New Record</a></span><br><br>

                <div class="table-responsive">
                    <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
                        <thead>
                        <th><input type="checkbox" id="checkall"/></th>
                        <th>ID</th>
                        <th>Store code</th>
                        <th>Лицензийн төрөл</th>
                        <th>Лицензийн төрлийн нэр</th>
                        <th>Лицензтэй эсэх</th>
                        <th>Лиценз авсан огноо</th>
                        <th>Лиценз дуусах огноо</th>
                        <th>Лиценз авсан ажилтан</th>
                        <th>Лиценз олгосон газрын нэр ID</th>
                        <th>Лиценз олгосон газар</th>
                        <th>Лицензийн код</th>
                        <th>Edit</th>
                        {% if user.is_authenticated %}
                            {% is_in_license_group as user_in_license_group %}
                            {% if user.is_superuser %}
                                <th>Delete</th>
                            {% elif user_in_license_group %}

                            {% endif %}
                        {% endif %}
                        </thead>
                        <tbody>
                        {% for model in models %}
                            <tr>
                                <td><input type="checkbox" class="checkthis"/></td>
                                <td>{{ model.id }}</td>
                                <td>{{ model.store_id }}</td>
                                <td>{{ model.lic_id }}</td>
                                <td>{{ model.lic_id_nm }}</td>
                                <td>{{ model.lic_yn }}</td>
                                <td>{{ model.st_dt }}</td>
                                <td>{{ model.ed_dt }}</td>
                                <td>{{ model.lic_owner }}</td>
                                <td>{{ model.lic_prov_ID }}</td>
                                <td>{{ model.lic_prov_name }}</td>
                                <td>{{ model.lic_no }}</td>
                                <td><a href="/edit/{{ model.id }}" class="btn btn-primary">Edit</a></td>
                                {% if user.is_authenticated %}
                                    {% is_in_license_group as user_in_event_group %}
                                    {% if user.is_superuser %}
                                        <td><a href="/delete{{ model.id }}" class="btn btn-danger">Delete</a></td>
                                    {% elif user_in_event_group %}

                                    {% endif %}
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
{#        <nav aria-label="Page navigation">#}
{#            <ul class="pagination">#}
{#                {% if page_obj.has_previous %}#}
{#                    <li class="page-item">#}
{#                        <a class="page-link" href="?page=1" aria-label="First">#}
{#                            <span aria-hidden="true">&laquo;&laquo;</span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="page-item">#}
{#                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">#}
{#                            <span aria-hidden="true">&laquo;</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% endif %}#}
{##}
{#                {% for num in page_obj.paginator.page_range %}#}
{#                    {% if page_obj.number == num %}#}
{#                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>#}
{#                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}#}
{#                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{##}
{#                {% if page_obj.has_next %}#}
{#                    <li class="page-item">#}
{#                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">#}
{#                            <span aria-hidden="true">&raquo;</span>#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="page-item">#}
{#                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">#}
{#                            <span aria-hidden="true">&raquo;&raquo;</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </nav>#}
{#        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>#}
{#        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>#}
{#        <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>#}
{##}
{#        <script>#}
{#            $(document).ready(function () {#}
{#                $('#bootstrapdatatable').DataTable({#}
{#                    "paging": false,#}
{#                    // other options#}
{#                });#}
{#            });#}
{##}
{#        </script>#}


    </div>{% endblock %}