cupp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views
from cupp.common import views as common_views
from cupp.point import views as point_views
from cupp.point.views import get_districts, custom_login_redirect
from cupp.license import views_lic as license_views
from cupp.event import views_event as event_views
from cupp.rent import views_rent as rent_views
from cupp.store_consultant import views as sc_views
from cupp.store_trainer import views as st_views
from cupp.competitors import views as comp_views
from cupp.master_api.views import StoreMasterAPI
from cupp.veritech_api.views import fetch_and_save_employee_data
from cupp.dispute import views as leg_views
# from cupp.powerBI_api.views import fetch_powerbi_data

# from cupp.ajax_table_list import ajax_table_list

urlpatterns = [

    path('save/', fetch_and_save_employee_data, name='save_employee_data'),
    # path('power/', fetch_powerbi_data, name='save_powerbi_data'),

    path('api/storemaster/', StoreMasterAPI.as_view(), name='storemaster-api'),

    path('ajax/get_districts/', get_districts, name='ajax_get_districts'),
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),

    # path('ajax/table-data/', ajax_table_list.get_table_data, name='ajax_table_data'),

    path('custom-login-redirect/', custom_login_redirect, name='custom_login_redirect'),

    path('groups/', point_views.display_groups, name='display-groups'),
    path('bi-embed/', point_views.bi_embed, name='bi-embed'),
    path('', point_views.index, name='event_index'),
    # path('register-license/', license_views.MainTableCreateView, name='register_license'),

    path('leg-index/', leg_views.index, name='leg-index'),
    path('leg-add/', leg_views.leg_add, name='leg-add'),
    path('leg-edit/<int:id>', leg_views.edit, name='leg-edit'),
    path('leg-update/<int:id>', leg_views.update, name='leg-update'),
    path('leg-delete/<int:id>', leg_views.destroy, name='leg-delete'),

    path('get-unallocated-stores/', sc_views.get_unallocated_stores, name='get_unallocated_stores'),

    path('sc-index/', sc_views.scIndex, name='sc-index'),
    path('store-index/', sc_views.index, name='store-index'),
    path('sc-view/<int:id>', sc_views.sc_view, name='sc-views'),
    path('sc-edit/<int:id>', sc_views.edit, name='sc-edit'),
    path('sc-update/<int:id>', sc_views.update, name='sc-update'),
    path('update_consultant_area/', sc_views.update_consultant_area, name='update_consultant_area'),
    # path('update_allocation/', sc_views.update_allocation, name='update_allocation'),
    path('save-allocations/', sc_views.save_allocations, name='save_allocations'),
    path('get-allocations/', sc_views.get_allocations, name='get_allocations'),
    path('get-team-data/<int:team_id>/', sc_views.get_team_data, name='get_team_data'),
    path('get-scs-by-team/<int:team_id>/', sc_views.get_scs_by_team, name='get_scs_by_team'),

    path('save-consultant-stores/', sc_views.save_consultant_stores, name='save-consultant-stores'),

    path('log-index/', event_views.index, name='event_index'),
    path('log-create', event_views.event_addnew, name='event-create'),
    path('log-edit/<int:id>', event_views.edit, name='event-edit'),
    path('log-update/<int:id>', event_views.update, name='event_update'),
    path('log-delete/<int:id>', event_views.destroy, name='log-delete'),

    path('comp-index/', comp_views.index, name='comp_index'),
    path('comp-create/', comp_views.comp_addnew, name='comp-create'),
    path('comp-edit/<int:id>', comp_views.edit, name='comp-edit'),
    path('comp-update/<int:id>', comp_views.update, name='comp_update'),
    path('comp-delete/<int:id>', comp_views.destroy, name='comp-delete'),

    path('rent-index/', rent_views.index, name='rent_index'),
    path('rent-create', rent_views.rent_addnew, name='rent-create'),
    path('rent-edit/<int:id>', rent_views.edit, name='rent-edit'),
    path('rent-update/<int:id>', rent_views.update, name='rent-update'),
    path('rent-delete/<int:id>', rent_views.destroy, name='rent-delete'),
    path('api/store-id-search/', rent_views.store_id_search, name='store_id_search'),

    path('st-index/', st_views.index, name='st-index'),
    path('st-view/<int:id>', st_views.st_view, name='st-view'),
    path('st-edit/<int:id>', st_views.edit, name='st-edit'),
    path('st-update/<int:id>', st_views.update, name='st-update'),
    # path('st-delete/<int:id>', st_views.destroy, name='st-delete'),

    path('register-license/', license_views.index, name='index'),
    path('addnew', license_views.addnew, name='addnew'),
    path('lic-edit/<int:id>', license_views.edit, name='lic-edit'),
    path('lic-update/<int:id>', license_views.update, name='lic-update'),
    # path('lic-delete/<int:id>/<str:table>/', license_views.destroy, name='lic-delete'),
    path('lic-delete/<int:id>', license_views.destroy, name='lic-delete'),

    path('map/', common_views.Map.as_view(), name='map'),
    path('my-settings/', common_views.MySettings.as_view(), name='my_settings'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('create/', point_views.Create.as_view(), name='point_create'),
    path('edit/<int:pk>/', point_views.Edit.as_view(), name='point_edit'),
    path('delete/<int:pk>/', point_views.Delete.as_view(), name='point_delete'),
    path('info/<int:pk>/', point_views.AjaxInfo.as_view(), name='point_ajax_info'),
    path('detail/<int:pk>/', point_views.Detail.as_view(), name='point_detail'),
    path('ajax-points/', point_views.AjaxList.as_view(), name='point_ajax_list'),

    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-recover/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-recover/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cupp.point.views.custom_404_view'

admin.site.site_title = 'PP Management'
admin.site.site_header = 'PP Management'
admin.site.index_title = 'Administration'

cupp/dispute/models.py
from django.db import models

# Create your models here.
from django.db import models
import os
import uuid

from django.db import models as m
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.conf import settings
from uuid import uuid4
from django.utils import timezone

from cupp.point.models import District, City
from cupp.event.models import ActionOwner


# Create your models here.
class DisputeTable(models.Model):
    five_digit_validator = RegexValidator(r'^\d{5}$', 'Store number must be a 5-digit number')
    date = models.DateField('Бодит үйл явдал болсон огноо')
    store_no = models.CharField('Үйл явдал болсон дэлгүүрийн дугаар', max_length=5, validators=[five_digit_validator],
                                blank=True, null=True)
    store_name = models.CharField(max_length=255, blank=True, null=True)
    disp_desc = models.TextField('Болсон хэргийн талаар дэлгэрэнгүй мэдээлэл')
    disp_cat = models.CharField('Хэргийн төрөл', max_length=50)
    dmg_amt = models.FloatField('Хохирлын хэмжээ /мөнгөн дүн/', default=0)
    dmg_uom = models.CharField('Хохирлын хэмжигдэхүүн', max_length=255)
    disp_owner = models.ForeignKey(ActionOwner, on_delete=m.CASCADE)
    disp_status = models.BooleanField('Хэргийн төлөв', blank=True, null=True)
    disp_progress = models.CharField('Хэргийн явц', max_length=500, blank=True, null=True)
    disp_result = models.BooleanField('Хэрэг шийдэгдсэн эсэх', blank=True, null=True)
    close_date = models.DateField('Хэрэг шийдэгдсэн өдөр', blank=True, null=True)
    supp_link = models.URLField('Холбогдох баримт бичгийн холбоос', blank=True, null=True)

    created_date = m.DateTimeField('Created date', auto_now_add=True, null=True)
    modified_date = m.DateTimeField('Modified date', auto_now=True, null=True)
    created_by = m.ForeignKey(User, verbose_name='Created by', related_name='dispute_created',
                              on_delete=m.PROTECT, null=True, blank=True)
    modified_by = m.ForeignKey(User, verbose_name='Modified by', related_name='dispute_modified',
                               on_delete=m.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.disp_cat

    def save(self, *args, **kwargs):
        if not self.pk and not self.created_by:
            self.created_by = self.modified_by
        super(DisputeTable, self).save(*args, **kwargs)

    class Meta:
        db_table = 'dispute'
        verbose_name = 'DisputeTable'

cupp/rent/models.py
from django.db import models
from cupp.store_trainer.models import StoreTrainer
from cupp.constants import CONTRACT_TYPE_CHOICES
from django.core.validators import RegexValidator


# Create your models here.


class StrRent(models.Model):
    five_digit_validator = RegexValidator(r'^\d{5}$', 'Store number must be a 5-digit number')
    store_id = models.CharField(max_length=5, validators=[five_digit_validator], null=True, blank=True)
    str_name = models.CharField('Салбарын нэр', null=True, max_length=200)
    str_address = models.CharField('Албан ёсны хаяг', null=True, max_length=200)
    lesser1 = models.CharField('Түрээслүүлэгч 1', null=True, max_length=100)
    lesser2 = models.CharField('Түрээслүүлэгч 2', null=True, max_length=100, blank=True)
    lesser3 = models.CharField('Түрээслүүлэгч 3', blank=True, null=True, max_length=100)
    phone_number1 = models.IntegerField('Холбоо барих утас 1', null=True, default=0)
    phone_number2 = models.IntegerField('Холбоо барих утас 2', null=True, default=0, blank=True)
    phone_number3 = models.IntegerField('Холбоо барих утас 3', blank=True, null=True, default=0)
    email = models.EmailField('И-майл хаяг', null=True)
    area_size = models.IntegerField('Талбайн нийт хэмжээ м.кв', null=True)
    cont_type = models.CharField('Contract Type', max_length=10, choices=CONTRACT_TYPE_CHOICES, null=True, blank=True)
    cntr_num1 = models.CharField('Гэрээний дугаар 1', null=True, max_length=30)
    cntr_num2 = models.CharField('Гэрээний дугаар 2', blank=True, null=True, max_length=30)
    cntr_num3 = models.CharField('Гэрээний дугаар 3', blank=True, null=True, max_length=30)
    st_dt = models.DateField('Гэрээ эхлэх хугацаа', null=True)
    ed_dt = models.DateField('Дуусах хугацаа ', null=True)
    ext_ed_dt = models.DateField('Сунгагдсан хугацаа', null=True)
    hand_over_dt = models.DateField('Талбай хүлээлцсэн актын өдөр', null=True)
    rent_mo_fee = models.IntegerField('Түрээсийн төлбөр ', null=True, default=0)
    rent_mo_fee_annex1 = models.IntegerField('Түрээсийн төлбөр 1', null=True, default=0, blank=True)
    rent_mo_fee_annex2 = models.IntegerField('Түрээсийн төлбөр 2', blank=True, null=True, default=0)
    rent_mo_fee_annex3 = models.IntegerField('Түрээсийн төлбөр 3', blank=True, null=True, default=0)
    deposit_amount = models.IntegerField('Барьцаа төлбөр', null=True, default=0)
    association_no = models.CharField('СӨХ гэрээний дугаар ', null=True, max_length=30)
    association_fee = models.IntegerField('СӨХ-ийн төлбөр', null=True, default=0)
    manage_cnt_no = models.CharField('Менежемент гэрээний дугаар', null=True, max_length=30)
    manage_fee = models.IntegerField('Менежментийн төлбөр', null=True, default=0)
    exp_inc = models.CharField('Гэрээнд орсон зардал', null=True, max_length=30)
    other_cnt = models.CharField('Бусад орлого болон зардлын гэрээ', null=True, max_length=30, blank=True)
    stora_yn = models.BooleanField('Stora box', null=True)
    stora_fee = models.IntegerField('Stora box түрээсийн төлбөр', null=True, default=0)
    atm_yn = models.BooleanField('ATM', null=True)
    atm_fee = models.IntegerField('ATM түрээсийн төлбөр', null=True, default=0)
    sublet_yn = models.BooleanField('Дамжуулан түрээслэх боломжтой эсэх', null=True)
    sublet1_cnt_no = models.CharField('1 Дамжуулан түрээсийн гэрээний дугаар', null=True, max_length=30, blank=True)
    sublet1_size = models.IntegerField('1 Дамжуулан түрээсийн талбай хэмжээ', null=True, default=0, blank=True)
    sublet1_rent = models.IntegerField('1 Дамжуулан түрээсийн үнэ ', null=True, default=0, blank=True)
    sublet1_deposit = models.IntegerField('1 Дамжуулан түрээсийн барьцаа төлбөр', null=True, default=0, blank=True)
    sublet2_cnt_no = models.CharField('2 Дамжуулан түрээсийн гэрээний дугаар', blank=True, null=True, max_length=30)
    sublet2_size = models.IntegerField('2 Дамжуулан түрээсийн талбай хэмжээ', blank=True, null=True, default=0)
    sublet2_rent = models.IntegerField('2 Дамжуулан түрээсийн үнэ', blank=True, null=True, default=0)
    sublet2_deposit = models.IntegerField('2 Дамжуулан түрээсийн барьцаа төлбөр', blank=True, null=True, default=0)
    sublet3_cnt_no = models.CharField('3 Дамжуулан түрээсийн гэрээний дугаар', blank=True, null=True, max_length=30)
    sublet3_size = models.IntegerField('3 Дамжуулан түрээсийн талбай хэмжээ', blank=True, null=True, default=0)
    sublet3_rent = models.IntegerField('3 Дамжуулан түрээсийн үнэ', blank=True, null=True, default=0)
    sublet3_deposit = models.IntegerField('3 Дамжуулан түрээсийн барьцаа төлбөр', blank=True, null=True, default=0)
    letter = models.CharField('Албан бичиг', blank=True, null=True, max_length=30)
    notice = models.CharField('Өргөдөл', blank=True, null=True, max_length=200)
    other_cont = models.CharField('Бусад гэрээ', blank=True, null=True, max_length=200)
    franchise_yn = models.BooleanField('Франчайз санал болгох заалттай', null=True)
    fr_rent_yn = models.BooleanField('Дамжуулан түрээсийн заалт', null=True)
    dedication = models.CharField('Үл хөдлөх хөрөнгийн зориулалт', null=True, blank=True, max_length=100)
    notariat_yn = models.BooleanField('Нотариат', null=True)
    real_estate_yn = models.BooleanField('ҮХХ-н гэрчилгээтэй эсэх', null=True)
    special_terms = models.CharField('Гэрээний онцгой нөхцөл', blank=True, null=True, max_length=30)
    cont_resp_term = models.CharField('Гэрээний хариуцлагын заалт', null=True, max_length=50)
    cont_link = models.CharField('Гэрээний холбоос', null=True, max_length=50)

    def __str__(self):
        return self.store_id

    class Meta:
        db_table = 'str_rent'
        verbose_name = 'Rent'

cupp/dispute/forms.py
from django import forms as f
from django.conf import settings
from .models import DisputeTable
from cupp.point.models import District, City
from cupp.event.models import ActionOwner


class DisputeForm(f.ModelForm):
    date = f.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    close_date = f.DateField(
        required=False,
        input_formats=settings.DATE_INPUT_FORMATS,
    )
    disp_desc = f.CharField(widget=f.Textarea(attrs={'class': 'form-control'}))
    dmg_amt = f.FloatField(widget=f.NumberInput(attrs={'class': 'form-control'}))
    supp_link = f.URLField(widget=f.URLInput(attrs={'class': 'form-control'}))
    disp_cat = f.ChoiceField(
        choices=[('', '---------'), ('ТАНХАЙ', 'ТАНХАЙ'), ('ДЭЭРЭМ', 'ДЭЭРЭМ'), ('ХУЛГАЙ', 'ХУЛГАЙ'),
                 ('ЗӨРЧИЛ', 'ЗӨРЧИЛ'), ('БУСАД', 'БУСАД')],
        widget=f.Select(attrs={'class': 'form-control'})
    )
    STATUS_CHOICE = [
        ('', '---------'),
        (True, 'Хаагдсан'),
        (False, 'Нээлттэй'),
    ]

    disp_status = f.ChoiceField(
        choices=STATUS_CHOICE,
        widget=f.Select(attrs={'class': 'form-control'}),
        initial=False  # Default to 'Нээлттэй'
    )

    RESULT_CHOICE = [
        ('', '---------'),
        (True, 'Yes'),
        (False, 'No')
    ]

    disp_result = f.ChoiceField(
        choices=RESULT_CHOICE,
        widget=f.Select(attrs={'class': 'form-control'}),
        initial=False  # Default to 'No'
    )

    store_no = f.CharField(widget=f.TextInput(attrs={'class': 'form-control'}), required=True)
    store_name = f.CharField(widget=f.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}), required=True)

    class Meta:
        model = DisputeTable
        fields = ['date', 'store_no', 'store_name', 'disp_desc', 'disp_cat', 'dmg_amt', 'dmg_uom',
                  'disp_status', 'disp_progress', 'disp_result', 'supp_link', 'disp_owner', 'close_date']

templates/Dispute/edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block header %}
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <form method="POST" class="post-form" action="{% url 'leg-update' model.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="container">
                <div class="col-12">
                    <h3>Update Details</h3>
                </div>
                <div class="form-group col-md-6">
                    <label>Дугаар: </label>
                    <input type="text" class="form-control" name="id" id="id_id" required readonly
                           value="{{ model.id }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Бодит үйл явдал болсон огноо:</label>
                    <input type="date" class="form-control" name="date" id="id_date"
                           value="{{ model.date|date:"Y-m-d" }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Дэлгүүрийн дугаар: <span class="text-purple">*</span></label>
                    <select id="id_store_no" class="form-control" name="store_no">
                        {% for store_id, store_name in store_id_to_name.items %}
                            <option value="{{ store_id }}" data-name="{{ store_name }}"
                                    {% if model.store_no == store_id %}selected{% endif %}>
                                {{ store_id }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Дэлгүүрийн нэр: <span class="text-purple">*</span></label>
                    <input id="id_store_name" value="{{ model.store_name }}" class="form-control"
                           name="store_name"
                           readonly type="text">
                </div>
                <div class="form-group col-md-6">
                    <label>Болсон хэргийн талаар дэлгэрэнгүй мэдээлэл: </label>
                    <textarea class="form-control" name="disp_desc" id="id_disp_desc" required
                              rows="5">{{ model.disp_desc }}</textarea>
                </div>
                <div class="form-group col-md-6">
                    <label>Хэргийн төрөл: <span class="text-purple">*</span></label>
                    <select name="disp_cat" id="id_disp_cat" class="form-control" required>
                        <option value="">{{ form.disp_cat.value|default_if_none:"Choose an option" }}</option>
                        <option value="ТАНХАЙ"
                                {% if model.disp_cat == "ТАНХАЙ" %}selected{% endif %}>
                            ТАНХАЙ
                        </option>
                        <option value="ДЭЭРЭМ"
                                {% if model.disp_cat == "ДЭЭРЭМ" %}selected{% endif %}>
                            ДЭЭРЭМ
                        </option>
                        <option value="ХУЛГАЙ"
                                {% if model.disp_cat == "ХУЛГАЙ" %}selected{% endif %}>
                            ХУЛГАЙ
                        </option>
                        <option value="ЗӨРЧИЛ"
                                {% if model.disp_cat == "ЗӨРЧИЛ" %}selected{% endif %}>
                            ЗӨРЧИЛ
                        </option>
                        <option value="БУСАД" {% if model.disp_cat == "БУСАД" %}selected{% endif %}>
                            БУСАД
                        </option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Хохирлын хэмжээ/ мөнгөн дүн: </label>
                    <input type="number" class="form-control" name="dmg_amt" id="id_dmg_amt" required
                           value="{{ model.dmg_amt }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Хохирлын хэмжигдэхүүн: </label>
                    <input type="text" class="form-control" name="dmg_uom" id="id_dmg_uom" required
                           value="{{ model.dmg_uom }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Хариуцагч: </label>
                    <select name="disp_owner" id="id_disp_owner" class="form-control">
                        {% for owner in owners %}
                            <option value="{{ owner.own_id }}"
                                    {% if dispute_table and dispute_table.disp_owner.id == owner.id %}selected{% endif %}>
                                {{ owner.own_pos }} - {{ owner.own_dep }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group col-md-6">
                    <label>Хэргийн төлөв: <span class="text-purple">*</span></label>
                    <select name="disp_status" id="id_disp_status" class="form-control" required>
                        <option value="">{{ disp_status }}</option>
                        <option value="False" {% if model.disp_status %}selected{% endif %}>Нээлттэй
                        </option>
                        <option value="True" {% if model.disp_status == False %}selected{% endif %}>
                            Хаагдсан
                        </option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Хэргийн явц: </label>
                    <input type="text" class="form-control" name="disp_progress" id="id_disp_progress"
                           required
                           value="{{ model.disp_progress }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Хэрэг шийдэгдсэн эсэх: <span class="text-purple">*</span></label>
                    <select name="disp_result" id="id_disp_result" class="form-control" required>
                        <option value="">{{ model.disp_result }}</option>
                        <option value="True" {% if model.disp_result %}selected{% endif %}>Тийм
                        </option>
                        <option value="False"
                                {% if model.disp_result == False %}selected{% endif %}>
                            Үгүй
                        </option>
                    </select>
                </div>
                {#            <div class="form-group col-md-6">#}
                {#                    <label>Бодит үйл явдал болсон огноо:</label>#}
                {#                    <input type="date" class="form-control" name="date" id="id_date"#}
                {#                           value="{{ model.date|date:"Y-m-d" }}"/>#}
                {#                </div>#}
                <div class="form-group col-md-6">
                    <label>Хэрэг шийдэгдсэн өдөр:</label>
                    <input type="date" class="form-control" name="close_date" id="id_close_date"
                           value="{{ model.close_date|default_if_none:''|date:'Y-m-d' }}"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Холбогдох баримт бичгийн холбоос:</label>
                    <input type="url" class="form-control" name="supp_link" id="id_supp_link"
                           value="{{ model.supp_link }}">
                </div>
                <div class="form-group col-md-6">
                    <a href="{% url 'index' %}" class="btn btn-link text-purple-300">
                        Cancel
                    </a>
                </div>
                <div class="form-group col-md-6">
                    <button type="submit" class="btn btn-success btn-lg">Update</button>
                </div>
            </div>
        </form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css"/>
        <script>
            $(document).ready(function () {
                $('#id_store_no').select2({
                    width: '100%',
                    placeholder: "Select a Store ID",
                });

                $('#id_store_no').change(function () {
                    var selectedName = $(this).find('option:selected').attr('data-name');
                    $('#id_store_name').val(selectedName);
                    $('#id_store_name').prop('readonly', true);
                });


                $('#id_date #id_close_date').daterangepicker({
                    singleDatePicker: true,
                    applyClass: 'bg-purple btn-sm',
                    cancelClass: 'btn-light btn-sm',
                    locale: {
                        format: 'YYYY/MM/DD'
                    }
                });
            });
        </script>
    </div>{% endblock content %}